services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: mygmanager-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL: http://localhost:3000
    container_name: mygmanager-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped